blueprint:
  name: Simple lights timer
  description: >
    
    **Version: 0.1**


  domain: automation
  author: https://github.com/kritsel
  homeassistant:
    min_version: "2024.6.0"
  input:

    lights_settings:
      name: "Lights *"
      icon: mdi:lightbulb-outline
      collapsed: true
      input:
        target_light:
          name: Lights
          description: >
            The lights that will be activated by the trigger sensor/s.
    
            **NOTE** - You can only use entities. Areas, devices and labels are not supported.
          default: []
          selector:
            target:
              entity:
                domain:
                  - light
                  - switch


    period_1_settings:
      name: "Lights on period 1"
      icon: mdi:clock-outline
      collapsed: true
      input:
        start_1_type:
          default: disable
          selector:
            select:
              options:
              - label: Use fixed time
                value: "time"
              - label: Use sun position
                value: "sun"
              - label: Disable start
                value: "disable"
        start_1_time:
          name: Fixed start time 1
          description: >
            Set the fixed start time for the first period.
          default: 00:00:00
          selector:
            time:
        start_1_sun:
          name: Sun position start time 1
          description: >
            Set the sun position for the start of the first period.
          default: start_1_sun_sunset
          selector:
            select:
              options:
                - label: Sunrise
                  value: "sunrise"
                - label: Sunset
                  value: "sunset"


variables:
  target_light: !input target_light
  start_1_type: !input start_1_type
  start_1_time: !input start_1_time
  start_1_sun: !input start_1_sun

triggers:
  - trigger: time
    id: "t_start_1_time"
    at: !input start_1_time
  - trigger: sun
    id: "t_sunrise"
    event: sunrise
  - trigger: sun
    id: "t_sunset"
    event: sunset

action:
  - choose:
      conditions:
      - condition: or
        conditions:
          - condition: and
            conditions:
            - condition: template
              value_template: "{{ start_1_type == 'time' }}"
            - condition: trigger
              id: "t_start_1_time"
          - condition: and
            conditions:
            - condition: template
              value_template: "{{ start_1_type == 'sun' }}"
            - condition: template
              value_template: "{{ start_1_sun == 'sunrise' }}"
            - condition: trigger
              id: "t_sunrise"
          - condition: and
            conditions:
              - condition: template
                value_template: "{{ start_1_type == 'sun' }}"
              - condition: template
                value_template: "{{ start_1_sun == 'sunset' }}"
              - condition: trigger
                id: "t_sunset"
        sequence:
          - service: light.turn_on
            data: {}
            target: !input target_light

mode: single