blueprint:
  name: RF 3-channel remote control - via RFLink
  domain: automation
  author: https://github.com/kritsel
  description: |
    description: >
    # RF 3-channel remote control - via RFLink
    
    The RFLink integration creates a single HomeAssistant entity to represent each of the channels of 
    a multi-channel RF (Radia Frequency) remote control. Plus an additional entity to support the 'All' or 'Group'
    channel when the remote supports that.
    This basic behaviour allows you to switch ON or OFF three separate entities (or group of entities 
    when you use HomeAssistant's `group` feature) via HomeAssistant. 
    
    
    This blueprint adds more control possibilities. 
    It allows you to associate independent actions to the ON and OFF button for each channel. 
    This essentially turns your RF channel remote control - meant to control *three* entities - 
    into a *six* button remote control where the ON and OFF button for each channel can each trigger 
    a completely independent (set of) action(s). 
    
    ## Prerequisites
    
    * Your RF remote control MUST be integrated via the RFLink integration.
    
    * The RFLink configuration must include `fire_event: true` for all HomeAssistant entities that represent
    the channels.
    See https://www.home-assistant.io/integrations/rflink/ for guidance.
    
    
    ## Examples of RF remote controls which are expected to work with this blueprint
    
    * COCO/KAKU APCR-2300R (https://klikaanklikuit.nl/product/stekkerschakelaarset-3-stekkers-2300-watt)
      (only has an ALL OFF button, no ALL ON)
    
    * COCO/KAKU APC3-2300RN (https://klikaanklikuit.nl/product/stekkerschakelaarset-3-stekkers-2300-watt-apc3-2300rn)
    
    ## 'All' or 'Group' functions
    The blueprint assumes that your RF remote control also supports an 'All' or 'Group' channel with an associated ON and
    OFF button. However, this functionality might not be available on every 3-channel remote control. 
    Some don't have an All/Group feature at all, or only have an OFF button for the 'All' channel and no ON.
    
    ## More Info
    
    ℹ️ ClickOnClickOff (KlikAanKlikUit in NL) is a Dutch brand that makes smart home and wireless remote control products.

  # user provided inputs
  input:
    # entities representing the buttons of the RF switch
    channel_1_entity:
      name: Channel 1 entity
      description: The entity representing channel 1.
      default: ''
      selector:
        entity:
          filter:
            - integration: rflink
              domain:
                - light
                - switch
                - binary_sensor
          multiple: false
    channel_2_entity:
      name: Channel 2 entity
      description: The entity representing channel 2.
      default: ''
      selector:
        entity:
          filter:
            - integration: rflink
              domain:
                - light
                - switch
                - binary_sensor
          multiple: false
    channel_3_entity:
      name: Channel 3 entity
      description: The entity representing channel 3.
      default: ''
      selector:
        entity:
          filter:
            - integration: rflink
              domain:
                - light
                - switch
                - binary_sensor
          multiple: false
    channel_all_entity:
      name: All/Group channel entity
      description: The entity representing the All or Group channel.
      default: ''
      selector:
        entity:
          filter:
            - integration: rflink
              domain:
                - light
                - switch
                - binary_sensor
          multiple: false

    # inputs for custom actions
    action_channel_1_on:
      name: (Optional) Channel 1 'on' press
      description: Action to run on channel 1 'on' press.
      default: []
      selector:
        action:
    action_channel_1_off:
      name: (Optional) Channel 1 'off' press
      description: Action to run on channel 1 'off' press.
      default: [ ]
      selector:
        action:
    action_channel_2_on:
      name: (Optional) Channel 2 'on' press
      description: Action to run on channel 2 'on' press.
      default: []
      selector:
        action:
    action_channel_2_off:
      name: (Optional) Channel 2 'off' press
      description: Action to run on channel 2 'off' press.
      default: [ ]
      selector:
        action:
    action_channel_3_on:
      name: (Optional) Channel 3 'on' press
      description: Action to run on channel 3 'on' press.
      default: []
      selector:
        action:
    action_channel_3_off:
      name: (Optional) Channel 3 'off' press
      description: Action to run on channel 3 'off' press.
      default: [ ]
      selector:
        action:
    action_channel_all_on:
      name: (Optional) All/Group 'on' press
      description: Action to run on All/Group 'on' press.
      default: [ ]
      selector:
        action:
    action_channel_all_off:
      name: (Optional) All/Group 'off' press
      description: Action to run on All/Group 'off' press.
      default: [ ]
      selector:
        action:

# Automation schema
mode: single
variables:
  # convert input tags to variables, so they can be used in templates
  channel_1_entity: !input channel_1_entity
  channel_2_entity: !input channel_2_entity
  channel_3_entity: !input channel_3_entity
  channel_all_entity: !input channel_all_entity

triggers:
  - trigger: event
    event_type:
      # RFLink fires button_pressed events for switches/lights/binary_sensors
      - button_pressed

conditions:
  # has the event been fired for one of the selected entities?
  - condition: template
    value_template: >-
      {{trigger.event.data.entity_id in [channel_1_entity,channel_2_entity,channel_3_entity,channel_all_entity] }}
  # and does the event contain a valid state?
  - condition: template
    value_template: >-
      {{trigger.event.data.state in ["on", "off"] }}

actions:
  - choose:
      # channel 1
      - conditions:
          - condition: template
            value_template: >-
              {{trigger.event.data.entity_id == channel_1_entity}}
        sequence:
          - choose:
              # 'on' click
              - conditions:
                  - condition: template
                    value_template: >-
                      {{trigger.event.data.state == "on"}}
                sequence: !input action_channel_1_on
              # 'off' click
              - conditions:
                  - condition: template
                    value_template: >-
                      {{trigger.event.data.state == "off"}}
                sequence: !input action_channel_1_off
      # channel 2
      - conditions:
          - condition: template
            value_template: >-
              {{trigger.event.data.entity_id == channel_2_entity}}
        sequence:
          - choose:
              # 'on' click
              - conditions:
                  - condition: template
                    value_template: >-
                      {{trigger.event.data.state == "on"}}
                sequence: !input action_channel_2_on
              # 'off' click
              - conditions:
                  - condition: template
                    value_template: >-
                      {{trigger.event.data.state == "off"}}
                sequence: !input action_channel_2_off
      # channel 3
      - conditions:
          - condition: template
            value_template: >-
              {{trigger.event.data.entity_id == channel_3_entity}}
        sequence:
          - choose:
              # 'on' click
              - conditions:
                  - condition: template
                    value_template: >-
                      {{trigger.event.data.state == "on"}}
                sequence: !input action_channel_3_on
              # 'off' click
              - conditions:
                  - condition: template
                    value_template: >-
                      {{trigger.event.data.state == "off"}}
                sequence: !input action_channel_3_off
      # all/group channel
      - conditions:
          - condition: template
            value_template: >-
              {{trigger.event.data.entity_id == channel_all_entity}}
        sequence:
          - choose:
              # 'on' click
              - conditions:
                  - condition: template
                    value_template: >-
                      {{trigger.event.data.state == "on"}}
                sequence: !input action_channel_all_on
              # 'off' click
              - conditions:
                  - condition: template
                    value_template: >-
                      {{trigger.event.data.state == "off"}}
                sequence: !input action_channel_all_off
