blueprint:
  name: RF 5-channel remote control for covers - via RFLink
  domain: automation
  author: https://github.com/kritsel
  description: |
    description: >
    # THIS BLUEPRINT IS UNTESTED
    
    # RF single channel remote control for covers - via RFLink
    
    This blueprint adds additional control possibilities to your RF (Radio Frequency) single channel remote for covers,
    when you have integrated that remote into your HomeAssistant via the RFLink integration.
    
    
    Out-of-the-box, the RFLink integration creates a single HomeAssistant entity to represent the remote's channel.
    This allows you to move your covers DOWN, UP or STOP movement via HomeAssistant dashboards, automations and scripts.
    
    
    This blueprint adds more control possibilities. 
    It allows you to assign independent HomeAssistant actions to the DOWN, UP and STOP commands for the channel. 
    This essentially turns your RF multi-channel remote 
    - originally meant to control only a **single** cover - 
    into a **three** button remote. With each DOWN, UP and STOP command for each channel
    able to trigger a completely independent (set of) HomeAssistant action(s). 
    So now you can for example also control Zigbee or Matter controlled devices 
    (like Philips Hue or IKEA lamps) via your RF remote you use to control your covers.      

    
    ## Prerequisites
    
    * Your RF remote control MUST be integrated via the RFLink integration.
    
    * The RFLink HomeAssistant entities you want to control belong to the `cover` domain.
    
    * The RFLink configuration must include `fire_event: true` for all HomeAssistant entities that represent
    the channels.
    See https://www.home-assistant.io/integrations/rflink/ for guidance.
    
    
    ## Examples of RF cover remote controls which work with this blueprint
    
    * Brel DC305 - single channel handheld transmitter for motors
    
    ## More Info
    
    
    ℹ️ [my blueprints on GitHub](https://github.com/kritsel/ha-blueprints)
  # user provided inputs
  input:
    # entities representing the channels supported by the RF remote control
    channel_1_entity:
      name: Channel 1 entity
      description: The cover entity representing channel 1.
      default: ''
      selector:
        entity:
          filter:
            - integration: rflink
              domain:
                - cover
          multiple: false

    # inputs for custom actions
    action_channel_1_up:
      name: Channel 1 UP
      description: Action to run on channel 1 UP press.
      default: []
      selector:
        action:
    action_channel_1_stop:
      name: Channel 1 STOP
      description: Action to run on channel 1 STOP press.
      default: [ ]
      selector:
        action:      
    action_channel_1_down:
      name: Channel 1 DOWN
      description: Action to run on channel 1 DOWN press.
      default: [ ]
      selector:
        action:

# Automation schema
mode: single
variables:
  # convert input tags to variables, so they can be used in templates
  channel_1_entity: !input channel_1_entity

triggers:
  - trigger: event
    event_type:
      # RFLink fires button_pressed events for the cover remotes
      - button_pressed

conditions:
  # has the event been fired for one of the selected entities?
  - condition: template
    value_template: >-
      {{trigger.event.data.entity_id in [channel_1_entity] }}
  # and does the event contain a valid state?
  - condition: template
    value_template: >-
      {{trigger.event.data.state in ["up", "down", "stop"] }}

actions:
  - choose:
      # channel 1
      - conditions:
          - condition: template
            value_template: >-
              {{trigger.event.data.entity_id == channel_1_entity}}
        sequence:
          - choose:
              # 'up' click
              - conditions:
                  - condition: template
                    value_template: >-
                      {{trigger.event.data.state == "ip"}}
                sequence: !input action_channel_1_up
              # 'stop' click
              - conditions:
                  - condition: template
                    value_template: >-
                      {{trigger.event.data.state == "stop"}}
                sequence: !input action_channel_1_stop
              # 'down' click
              - conditions:
                  - condition: template
                    value_template: >-
                      {{trigger.event.data.state == "down"}}
                sequence: !input action_channel_1_down
